### ISSUE TITLE
Add ability to add own ipfs link

### ISSUE THREAD

**Issue by codingshot** [codingshot/genadrop#726]
Detect if valid ipfs link or decentralized storage solutions instead of upload page. This way we can have other ppl use their own storage solution and stop paying. Show toast notification invalid ipfs link. Need frames for it but similar to tweet ui

**Comment by codingshot** [comment]
designs have been made

**Comment by Prometheo** [comment]
this issue has been completed in the pr: [https://github.com/codingshot/genadrop/tree/ipfs](https://github.com/codingshot/genadrop/tree/ipfs)
