### ISSUE TITLE
NEAR NFTs not minting to receiver adress

### ISSUE THREAD

**Issue by codingshot** [codingshot/genadrop#793]
NEAR NFTs not minting to receiver address

**Comment by codingshot** [comment]
also if i transfer outside of application it doesnt show under transaction history

**Comment by Prometheo** [comment]
This as been resolved with proof:
https://explorer.near.org/transactions/DS3z8W2Fmb7TaKeAHUhSYAMhS4zxdPvK8zUCoYr7gTUw
