### ISSUE TITLE
NEAR Marketplace Listing to Multiple Marketplaces

### ISSUE THREAD

**Issue by codingshot** [codingshot/genadrop#861]
Listen for solds, list all the fees for each marketplace in the UI

have front end dev do this, also designer should be on this

https://explorer.mainnet.near.org/accounts/apollo42.near
https://explorer.mainnet.near.org/accounts/marketplace.paras.near
https://explorer.mainnet.near.org/accounts/market.fewandfar.near
https://explorer.mainnet.near.org/accounts/market.tradeport.near

**Comment by Prometheo** [comment]
listing to tradeport and few and far implemented,
reference PR: https://github.com/codingshot/genadrop/pull/942
