### ISSUE TITLE
ability to scan QR code for mint to another address

### ISSUE THREAD

**Issue by codingshot** [codingshot/genadrop#964]
# Features
- when it says mint to another adress, there should be a QR code scanner icon that pulls up camera (especially for mobile) and allows to scan someone else's address 
- Check for valid crypto address
- need quick designs
# Why
- easily allow other people to mint to an address in real life, example POAPs, event activations

# Estimated Engineering Time
- 1 hour

# Available Resources

**Comment by Amichael10** [comment]
![Upload](https://user-images.githubusercontent.com/89662604/215489013-586369a3-f82c-4ddd-bc3f-4258a57d21e3.png)
https://www.figma.com/file/GinQzBfws9gl6PZZ5y9ZvV/Genadrop-Design?node-id=12325%3A126732&t=5lsQa9dA2FaCFwaj-11
